# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import host_pb2 as host__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in host_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HostControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TelemetryStream = channel.stream_stream(
                '/host.HostControl/TelemetryStream',
                request_serializer=host__pb2.HostMessage.SerializeToString,
                response_deserializer=host__pb2.HostMessage.FromString,
                _registered_method=True)
        self.CommandStream = channel.stream_stream(
                '/host.HostControl/CommandStream',
                request_serializer=host__pb2.HostMessage.SerializeToString,
                response_deserializer=host__pb2.HostMessage.FromString,
                _registered_method=True)
        self.MotorControlStream = channel.stream_stream(
                '/host.HostControl/MotorControlStream',
                request_serializer=host__pb2.HostMessage.SerializeToString,
                response_deserializer=host__pb2.HostMessage.FromString,
                _registered_method=True)


class HostControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TelemetryStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MotorControlStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HostControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TelemetryStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TelemetryStream,
                    request_deserializer=host__pb2.HostMessage.FromString,
                    response_serializer=host__pb2.HostMessage.SerializeToString,
            ),
            'CommandStream': grpc.stream_stream_rpc_method_handler(
                    servicer.CommandStream,
                    request_deserializer=host__pb2.HostMessage.FromString,
                    response_serializer=host__pb2.HostMessage.SerializeToString,
            ),
            'MotorControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.MotorControlStream,
                    request_deserializer=host__pb2.HostMessage.FromString,
                    response_serializer=host__pb2.HostMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'host.HostControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('host.HostControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HostControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TelemetryStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/host.HostControl/TelemetryStream',
            host__pb2.HostMessage.SerializeToString,
            host__pb2.HostMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommandStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/host.HostControl/CommandStream',
            host__pb2.HostMessage.SerializeToString,
            host__pb2.HostMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MotorControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/host.HostControl/MotorControlStream',
            host__pb2.HostMessage.SerializeToString,
            host__pb2.HostMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
