# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: host.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'host.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhost.proto\x12\x04host\"A\n\x0bHostMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x11\n\trecipient\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t2\xc5\x01\n\x0bHostControl\x12;\n\x0fTelemetryStream\x12\x11.host.HostMessage\x1a\x11.host.HostMessage(\x01\x30\x01\x12\x39\n\rCommandStream\x12\x11.host.HostMessage\x1a\x11.host.HostMessage(\x01\x30\x01\x12>\n\x12MotorControlStream\x12\x11.host.HostMessage\x1a\x11.host.HostMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'host_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOSTMESSAGE']._serialized_start=20
  _globals['_HOSTMESSAGE']._serialized_end=85
  _globals['_HOSTCONTROL']._serialized_start=88
  _globals['_HOSTCONTROL']._serialized_end=285
# @@protoc_insertion_point(module_scope)
